backend: # Uncomment at need
  # GitHub backend
  name: github
  repo: nebulab/playbook
  branch: middleman-subfolder-v2 # Branch to update (optional; defaults to master) repository

  # Local testing
  # name: test-repo

publish_mode: editorial_workflow

media_folder: middleman/uploads
public_folder: /middleman/uploads

logo_url: /middleman/assets/logo.png

collections:
  - label: Home
    name: home
    files:
      - file: index.html.md
        label: Homepage
        name: homepage
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
  - label: Sections
    name: sections
    files:
      - file: about-us.html.md
        label: About us
        name: about-us
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: about-us-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: how-we-work.html.md
        label: How we work
        name: how-we-work
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: how-we-work-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: personal-growth.html.md
        label: Personal growth
        name: personal-growth
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: personal-growth-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: people-ops.html.md
        label: People operations
        name: people-ops
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: people-ops-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: the-offices.html.md
        label: The offices
        name: the-offices
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: the-offices-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: working-on-nebulab.html.md
        label: Working on Nebulab
        name: working-on-nebulab
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: working-on-nebulab-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: development.html.md
        label: Development
        name: development
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: development-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
      - file: useful-resources.html.md
        label: Useful resources
        name: useful-resources
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Position
            name: position
            widget: number
            required: true
            valueType: int
            min: 1
          - label: Chapters
            name: playbook-section-chapters
            label_singular: chapter
            widget: list
            field:
              label: Chapter
              name: playbook-section-chapter
              widget: relation
              collection: useful-resources-section-chapters
              searchFields:
                - title
              valueField: title
          - label: Body
            name: body
            widget: markdown
  - label: '"About us" section chapters'
    name: about-us-section-chapters
    label_singular: '"About us" section chapter'
    folder: about-us/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"How we work" section chapters'
    name: how-we-work-section-chapters
    label_singular: '"How we work" section chapter'
    folder: how-we-work/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"Personal growth" section chapters'
    name: personal-growth-section-chapters
    label_singular: '"Personal growth" section chapter'
    folder: personal-growth/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"People operations" section chapters'
    name: people-ops-section-chapters
    label_singular: '"People operations" section chapter'
    folder: people-ops/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"The offices" section chapters'
    name: the-offices-section-chapters
    label_singular: '"The offices" section chapter'
    folder: the-offices/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"Working on Nebulab" section chapters'
    name: working-on-nebulab-section-chapters
    label_singular: '"Working on Nebulab" section chapter'
    folder: working-on-nebulab/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"Development" section chapters'
    name: development-section-chapters
    label_singular: '"Development" section chapter'
    folder: development/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
  - label: '"Useful resources" section chapters'
    name: useful-resources-section-chapters
    label_singular: '"Useful resources" section chapter'
    folder: useful-resources/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
