backend: # Uncomment at need
  # GitHub backend
  name: github
  repo: nebulab/playbook
  branch: middleman # Branch to update (optional; defaults to master) repository

  # Local testing
  # name: test-repo

publish_mode: editorial_workflow

media_folder: source/images/uploads
public_folder: /images/uploads

logo_url: /assets/images/logo.png

collections:
  - label: Home
    name: home
    files:
      - file: source/index.html.md
        label: Homepage
        name: homepage
        format: frontmatter
        create: false
        delete: false
        slug: '{{title}}'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
      - file: data/home/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation items
            name: navigation_items
            widget: list
            fields:
              - label: Image
                name: image_path
                widget: image
              - label: Caption
                name: caption
                widget: string
              - label: Link
                name: link
                widget: string
  - label: Playbook sections
    name: playbook-sections
    label_singular: Playbook section
    folder: source/playbook/sections/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Topics
        name: playbook-section-topics
        label_singular: topic
        widget: list
        field:
          label: Topic
          name: playbook-section-topic
          widget: relation
          collection: playbook-topics
          searchFields:
            - title
          valueField: title
      - label: Body
        name: body
        widget: markdown
  - label: Playbook topics
    name: playbook-topics
    label_singular: Playbook topic
    folder: source/playbook/topics/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
